version: '3.8'

services:
  jmeter:
    image: asarwardev/jmeter
    volumes:
      - ./bin:/opt/apache-jmeter/bin
      - ./lib:/opt/apache-jmeter/lib
    deploy:
      mode: replicated
      replicas: 6