version: '3.8'

services:
  jmeter:
    image: asarwardev/jmeter
    volumes:
      - ./bin:/opt/apache-jmeter/bin
      - ./lib:/opt/apache-jmeter/lib
    command: 
      -sh runner.sh
    depends_on:
      - influxdb
    
  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - influxdb:/var/lib/influxdb/data:rw
    ports:
      - 8086:8086
      - 2003:2003
    environment:
      - INFLUXDB_GRAPHITE_ENABLED = true
      - INFLUXDB_GRAPHITE_DATABASE = 'jmeter'
    container_name: influxdb

  grafana:
    image: grafana/grafana:main
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    container_name: grafana
    
  volumes:
    influxdb

    